.github/workflows/server-ci.yml
=> chore: add github action yml for CI

server/package.json, server/src/controllers/questions.ts, server/src/middlewares/customErrorHandler.ts, server/src/models/Answer.ts, server/src/models/Question.ts, server/src/models/User.ts, server/src/models/Util.ts, server/src/routes/questions.ts, server/src/services/database.ts, server/src/services/server.ts, server/src/utils/HttpStatusCode.ts, server/src/utils/errors/ApiError.ts, server/src/utils/errors/ApiErrorMessage.ts, server/tests/routes/questions.test.ts, server/tests/services/database.test.ts, server/yarn.lock
=> feat: add CRUD functionalities for questions

README.md
=> added instructions for client

README.md
=> docs: add answers api reference for server

README.md, server/package.json, server/src/controllers/questions.ts, server/src/routes/questions.ts, server/src/utils/errors/ApiErrorMessage.ts, server/src/utils/titleToSlug.ts, server/tests/routes/questions.test.ts, server/tests/utils/titleToSlug.test.ts, server/yarn.lock
=> server: update questions API to accommodate new database schema

server/src/middlewares/customErrorHandler.ts
=> fix: make API errors return json data to caller

README.md
=> docs: update setup info and API ref for firebase auth

README.md, server/src/controllers/questions.ts, server/src/routes/questions.ts, server/src/utils/errors/ApiErrorMessage.ts, server/src/utils/types/GetQuestionRequestResponse.ts, server/tests/controllers/questions.test.ts, server/tests/routes/questions.test.ts
Add pagination for server. Deals with #55
=> Feat: added pagination to server

client/components/api/questions.ts, client/components/api/util.ts, client/package.json, client/pages/forum/index.tsx, client/util/types.ts, client/yarn.lock
=> client: Feat integrate pagination

README.md, client/components/questions/AnswerForm.tsx, client/components/questions/AnswerPreview.tsx, client/components/questions/ViewAnswersCard.tsx, client/components/questions/ViewAnswersCardListItem.tsx, client/components/questions/index.module.css, client/pages/question/[qid]/[slug]/index.tsx, client/utils/api/answers.ts, client/utils/api/index.ts, client/utils/types/apiReqRes.ts, client/utils/types/models.ts, server/src/routes/answers.ts
=> client: integrate with answers API

client/components/questions/ViewAnswersCard.tsx, client/components/questions/ViewAnswersCardListItem.tsx
=> fix: conditionally render create answer form based on auth

README.md, server/src/controllers/answers.ts, server/src/controllers/questions.ts, server/src/routes/users.ts
=> server: add user endpoints

client/components/questions/UpvoteDownvote.tsx, client/utils/hooks/index.ts, client/utils/hooks/useUpvoteDownvote.ts, server/src/controllers/questions.ts
To replicate the logic for answers. can just import and use this hook in any component that requires upvote downvote. Just remember to follow the props and pass the necessary API calls
=> Client: custom hook for upvote downvote

client/components/authentication/index.tsx, client/components/questions/AnswerForm.tsx, client/components/questions/QuestionForm.tsx, client/components/questions/QuestionUpvoteDownvote.tsx, client/components/questions/ViewAnswersCard.tsx, client/components/questions/ViewAnswersCardListItem.tsx, client/components/questions/ViewQuestionCard.tsx, client/components/questions/index.tsx, client/utils/api/answers.ts, client/utils/api/questions.ts, client/utils/api/util.ts, client/utils/constants/voteType.ts, client/utils/helpers/firebaseAuthUtils.ts, client/utils/hooks/useUpvoteDownvote.ts, client/utils/index.ts, client/utils/types/apiReqRes.ts
- User's `idToken` is now cached in `useAuth` hook to prevent calling `getIdToken` multiple times (may have to optimise in future to refresh the token at certain intervals)
- Add vote functionality to answers
closes #85
=> Client: integrate with answers vote API

server/src/controllers/questions.ts, server/src/routes/questions.ts, server/src/services/database.ts, server/src/utils/types/questionTypes.ts
Searched using $text and $search
Close #55
=> Fuzzy search

client/components/landing/index.tsx, client/components/landing/landing.module.css
=> misc additions

README.md
=> docs: fix analytics api ref

README.md, server/src/controllers/answers.ts, server/src/routes/answers.ts, server/src/routes/questions.ts
=> server: Add sorting options to answers

README.md, server/cloudbuild.yaml, server/package.json, server/src/index.ts, server/src/utils/helpers/envUtils.ts, server/tests/controllers/questions.test.ts, server/tests/controllers/users.test.ts, server/tests/controllers/votes.test.ts, server/tests/middlewares/authRouteHandler.test.ts, server/tests/middlewares/customErrorHandler.test.ts, server/tests/services/database.test.ts, server/tests/utils/envUtils.test.ts
=> server: deployment to GCP

server/src/controllers/answers.ts
=> server: Sort by upvotes if nett votes are the same

server/src/controllers/analytics.ts, server/src/routes/analytics.ts, server/src/services/server.ts, server/src/utils/types/analyticsTypes.ts, server/src/utils/types/userTypes.ts
=> server feat: analytics

client/components/user/index.tsx, client/pages/forum/index.tsx, client/pages/question/ask/index.tsx, client/pages/user/[username].tsx, client/utils/api/user.ts, client/utils/api/util.ts, client/utils/types/apiReqRes.ts, client/utils/types/models.ts, server/src/routes/analytics.ts
=> fix user fetching and layout

client/pages/question/ask/index.tsx, client/utils/types/models.ts
=> Client: fix misc 

server/src/controllers/analytics.ts, server/src/utils/types/analyticsTypes.ts
For questions and answers in analytics api
=> full-document-return

server/src/controllers/analytics.ts, server/src/controllers/answers.ts, server/src/controllers/questions.ts, server/src/controllers/votes.ts, server/src/utils/types/analyticsTypes.ts
=> server: get recently voted answers and questions

client/components/landing/index.tsx, client/components/landing/landing.module.css, client/components/questions/AnswerPreview.tsx, client/components/questions/QuestionPreview.tsx, client/components/questions/ViewQuestionCard.tsx, client/components/user/AnswerDisplay.tsx, client/components/user/QuestionDisplay.tsx, client/components/user/index.tsx, client/pages/question/[qid]/[slug]/edit/index.tsx, client/pages/question/ask/index.tsx, client/pages/user/[username].tsx, client/utils/helpers/dateUtils.ts, client/utils/types/apiReqRes.ts, server/src/controllers/analytics.ts, server/src/utils/types/analyticsTypes.ts, server/src/utils/types/index.ts
=> client: overall design tweaks
